function figdppcyto(n)
%{ 
Updated list:

2015.10.23 George

%}
%CREATEFIGURE(CDATA1, X1, Y1)
%  CDATA1:  image cdata
%  X1:  vector of x data
%  Y1:  vector of y data

gene=n;
xrange=[];
yrange=[];

%  Auto-generated by MATLAB on 22-Oct-2015 04:31:57
load('cytoneme.mat');
cdata1=sta_all{1,gene}.dpp;cdata2=sta_all{1,gene}.dpp_y;
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse',...
    'Position',[0.0445168295331162 0.11 0.92399565689468 0.815],...
    'Layer','top');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.5 120.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0.5 50.5]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create plot
for i=1:size(sta_all{1,gene}.cyto,2)
    X1=[sta_all{1,gene}.cyto(2,i) sta_all{1,gene}.cyto(6,i)];
    Y1=[sta_all{1,gene}.cyto(1,i) sta_all{1,gene}.cyto(5,i)];
    if isempty(xrange)~=1
        if min(xrange)<min(X1)&&max(xrange)<min(X1)
        elseif min(xrange)>max(X1)&&max(xrange)>max(X1)
        else
            if isempty(yrange)~=1
                if min(yrange)<min(Y1)&&max(yrange)<min(Y1)
                elseif min(yrange)>max(Y1)&&max(yrange)>max(Y1)
                else
                    eval(['plot(X1,Y1,''Visible'',''on'',''DisplayName'',''(' num2str(Y1(1)) ',' num2str(X1(1)) ') to (' num2str(Y1(2)) ',' num2str(X1(2)) ')'');']);
                end                
            else
                eval(['plot(X1,Y1,''Visible'',''on'',''DisplayName'',''(' num2str(Y1(1)) ',' num2str(X1(1)) ') to (' num2str(Y1(2)) ',' num2str(X1(2)) ')'');']);
            end
        end
    else
        if isempty(yrange)~=1
            if min(yrange)<min(Y1)&&max(yrange)<min(Y1)
            elseif min(yrange)>max(Y1)&&max(yrange)>max(Y1)
            else
                eval(['plot(X1,Y1,''Visible'',''on'',''DisplayName'',''(' num2str(Y1(1)) ',' num2str(X1(1)) ') to (' num2str(Y1(2)) ',' num2str(X1(2)) ')'');']);
            end                
        else
            eval(['plot(X1,Y1,''Visible'',''on'',''DisplayName'',''(' num2str(Y1(1)) ',' num2str(X1(1)) ') to (' num2str(Y1(2)) ',' num2str(X1(2)) ')'');']);
        end
    end
end

figure2=figure;
plot(cdata2);
end

